# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Publish a Docker image

on:
  workflow_dispatch:
  #push:
  #  branches: ['main']

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1

      - name: 'Login via Azure CLI'
        uses: azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@15c4aadf093404726ab2ff205b2cdd33fa6d054c
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/todoapp:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/todoapp:latest
               
      - name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/todoapp:latest
          dockerfile: ./Dockerfile

      - name: Upload SARIF file
        if: ${{ steps.scan.outputs.sarif != '' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v4.0.3
        with:
          resource-group: '${{ secrets.RESOURCE_GROUP }}' 
          cluster-name: '${{ secrets.CLUSTER_NAME }}'

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v4.0.1

      - name: Create Secret
        uses: azure/k8s-create-secret@v5.0.1
        with:
          namespace: default
          secret-name: mongodb-secrets
          secret-type: generic
          data: ${{ secrets.MONGODB_URI }}

      - name: Create Secret
        uses: azure/k8s-create-secret@v5.0.1
        with:
          namespace: default
          secret-name: secret-key
          secret-type: generic
          data: ${{ secrets.SECRET_KEY }}

      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v5.0.4
        with:
          namespace: 'default'
          manifests: |
             deployment.yaml
          images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/todoapp:latest'
          pull-images: false 


