# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Publish PR Scan

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']
  #push:
  #  branches: ['main']

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  container-scan:
    name: Scan Docker Image in PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v6.0.1

      - name: Build Docker image
        run: docker build . -t todoapp:latest

      # Scan image with Trivy
      - name: Scan Docker image with Trivy
        id: scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: todoapp:latest
          format: 'table'
          output: 'trivy-results.txt'
          ignore-unfixed: true
          scanners: 'vuln,secret,misconfig'
          severity: 'CRITICAL,HIGH'

      - name: Comment Trivy Results on PR
        uses: marocchino/sticky-pull-request-comment@v2.9.4
        with:
          path: trivy-results.txt

      - name: Write PR Results to Summary
        run: |
          echo "## Trivy Scan Results (Table)" >> $GITHUB_STEP_SUMMARY
          cat trivy-results.txt >> $GITHUB_STEP_SUMMARY






