name: Deploy Infrastructure

on:
 workflow_dispatch:
   inputs:
      action:
        description: 'Create or Destroy'
        required: true
        type: choice
        options:
          - apply
          - destroy

jobs:
  deploy:
    name: ${{ inputs.action }} Infrastructure
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.14.1
          cli_config_credentials_token: ${{ secrets.TF_TOKEN}}

      - run: |
          cd ${{ github.workspace }}/infrastructure
          echo "Action is ${ACTION}"
          terraform init
          if [ "${ACTION}" = "apply" ]; then
            terraform "${ACTION}" -target="azurerm_kubernetes_cluster.aks_cluster" -auto-approve 
            sleep 60
            terraform "${ACTION}" -target="helm_release.cert_manager" -auto-approve
            sleep 60
            terraform "${ACTION}" -target="helm_release.nginx_ingress" -auto-approve
            sleep 60
            terraform "${ACTION}" -auto-approve
          else
            terraform "${ACTION}" -auto-approve
          fi
        env:
          ACTION: ${{ inputs.action }}
