name: Deploy Infrastructure

on:
 workflow_dispatch:
   inputs:
      action:
        description: 'Create or Destroy'
        required: true
        type: choice
        options:
          - apply
          - destroy

jobs:
  deploy:
    name: ${{ inputs.action }} Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace Tokens
        uses: cschleiden/replace-tokens@v1.3
        with:
          files: ["${{ github.workspace }}/infrastructure/main.tf"]
          tokenPrefix: '@@@'
          tokenSuffix: '@@@'
        env:
          MONGODB_ADMIN_PWD: ${{ secrets.MONGODB_ADMIN_PWD }}
          MONGODB_APP_USER_PWD: ${{ secrets.MONGODB_APP_USER_PWD }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.14.1
          cli_config_credentials_token: ${{ secrets.TF_TOKEN}}

      - run: |
          cd ${{ github.workspace }}/infrastructure
          terraform init
          terraform $ACTION --auto-approve
        env:
          ACTION: ${{ inputs.action }}
