name: Deploy Infrastructure

on:
 workflow_dispatch:
   inputs:
      action:
        description: 'Create or Destroy'
        required: true
        type: choice
        options:
          - apply
          - destroy

jobs:
  deploy:
    name: ${{ inputs.action }} Infrastructure
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@latest
        id: msdo
        with:
          tools: 'terrascan'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@cf1bb45a277cb3c205638b2cd5c984db1c46a412
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.14.1
          cli_config_credentials_token: ${{ secrets.TF_TOKEN}}

      - run: |
          cd ${{ github.workspace }}/infrastructure
          terraform init
          if [ "${ACTION}" = "apply" ]; then
            terraform "${ACTION}" -target="azurerm_kubernetes_cluster.aks_cluster" -auto-approve 
            sleep 60
            terraform "${ACTION}" -auto-approve
          else
          terraform "${ACTION}" -auto-approve
        env:
          ACTION: ${{ inputs.action }}
